---
## stages:
##   - puppetsync::checkout_git_feature_branch_in_each_repo
##   - puppetsync::install_gems
##   - puppetsync::ensure_jira_subtask_for_each_repo
##   - puppetsync::ensure_github_fork
##   - puppet_apply
##   - puppetsync::git_commit
##   - puppetsync::ensure_github_pr

jira:
  parent_issue: SIMP-7035
  project: SIMP
  jira_site: https://simp-project.atlassian.net
  subtask_title: 'Update .travis.yml pipeline in %COMPONENT%'
  # optional:
  subtask_story_points: 1
  subtask_description: 'Push the new (static) Travis CI pipelines to %COMPONENT%'
  subtask_assignee: 'chris.tessmer'

github:
  user: op-ct

git:
  commit_message: |
    (%JIRA_PARENT_ISSUE%) Update to new Travis CI pipeline

    This patch updates the Travis Pipeline to a static, standardized format
    that uses project variables for secrets. It includes an optional
    diagnostic mode to test the project's variables against their respective
    deployment APIs (GitHub and Puppet Forge).

    [%JIRA_PARENT_ISSUE%] #comment Update to latest pipeline in %COMPONENT%
    [%JIRA_SUBTASK%] #close
