---

puppetsync:
  puppet_role: 'role::pupmod_gitlabci_only'
  permitted_project_types:
    - pupmod
  plans:
    sync:
      # TODO: make this `stages` that opt-in, not opt out
      skip_pipeline_stages:
      #  - install_gems
      #  - checkout_git_feature_branch_in_each_repo
      #  - split_gitlab_files
        - ensure_jira_subtask
      # - apply_puppet_role
      # - git_commit_changes
        - ensure_github_fork
        - ensure_git_remote
        - git_push_to_remote
        - ensure_github_pr
      #clone_git_repos: false

    approve_github_pr:
      clone_git_repos: false
    merge_github_pr:
      clone_git_repos: false


jira:
  parent_issue: SIMP-7708
  project: SIMP
  jira_site: https://simp-project.atlassian.net
  subtask_title: 'Fix .gitlab-ci.yml cache setting in %COMPONENT%'
  # optional:
  subtask_story_points: 1
  subtask_description: 'Fix .gitlab-ci.yml cache setting in %COMPONENT%'
  subtask_assignee: 'chris.tessmer'

git:
  # 0---------1---------2---------3---------4---------5---------6---------7-|
  commit_message: |
    (%JIRA_PARENT_ISSUE%) Fix Gitab CI cache setting

    This patch removes the gitlab cache `untracked: true` setting from
    `.gitlab-ci.yml`.

    [%JIRA_PARENT_ISSUE%] #comment Update to latest pipeline in %COMPONENT%
    %JIRA_SUBTASK% #close

github:
  pr_user: op-ct
  approval_message: ':+1: :ghost:'
