---

puppetsync:
  permitted_project_types:
    - pupmod
    - pupmod_skeleton
  plans:
    sync:
      #clone_git_repos: false
      stages:
        # - install_gems
        - checkout_git_feature_branch_in_each_repo
        - ensure_jira_subtask
        - apply_puppet_role
        - modernize_gitlab_files
        - lint_gitlab_ci
        - git_commit_changes
        - ensure_github_fork
        - ensure_git_remote
        - git_push_to_remote
        - ensure_gitlab_remote
        - git_push_to_gitlab
        - ensure_github_pr
#
    approve_github_pr:
      clone_git_repos: false
      stages:
        - install_gems
        - approve_github_pr_for_each_repo

    merge_github_pr:
      clone_git_repos: false
      stages:
        - install_gems
        - merge_github_pr_for_each_repo

jira:
  parent_issue: SIMP-7974
  project: SIMP
  jira_site: https://simp-project.atlassian.net
  subtask_title: 'Add new GLCI pipeline features to %COMPONENT%'
  # optional:
  subtask_story_points: 1
  subtask_description: 'Add new GLCI pipeline features to %COMPONENT%'
  subtask_assignee: true

git:
  # 0---------1---------2---------3---------4---------5---------6---------7-|
  # (SIMP-XXXX) 12345678
  commit_message: |
    (%JIRA_PARENT_ISSUE%) Add new GLCI pipeline features

    The patch adds enhanced features to SIMP Puppet modules' standardized
    GitLab CI pipeline:

    * spec and acceptance tests _only_ run when relevant files have changed
    * The CI variable `SIMP_FULL_MATRIX` is replaced by `SIMP_MATRIX_LEVEL`
    * spec and acceptance tests run at or above their `SIMP_MATRIX_LEVEL`
    * Jobs and the pipeline default to `SIMP_MATRIX_LEVEL` 1
    * The pipeline's `SIMP_MATRIX_LEVEL` can be changed via CI variable
      (via triggers, group/project settings, etc)
    * In the pipeline-triggering commit message, adding a line that starts
      with `CI: MATRIX LEVEL 0` or `CI: SKIP MATRIX` will suppress all steps
      with `SIMP_MATRIX_LEVEL` 1-3

    There is an important caveat: because of the way GitLab CI pipelines
    determine `changes`, a file that hasn't changed between `--amend` +
    force-pushed updates _will not trigger the matrix again_.  This affects
    scheduled and triggered pipelines.

    * To solve this scenario, setting the CI variable `SIMP_FORCE_MATRIX =
      yes` in a scheduled pipeline or pipeline trigger will ensure that all
      jobs at the current `SIMP_MATRIX_LEVEL` are run, regardless of what
      has changed (or not).

    CI: SKIP_MATRIX
    %JIRA_SUBTASK% #close
    [%JIRA_PARENT_ISSUE%] #comment Add file-match CI runs to %COMPONENT%
    [SIMP-7975] #comment Add `SIMP_MATRIX_LEVEL` checks to %COMPONENT%

    [SIMP-7974]: https://simp-project.atlassian.net/browse/SIMP-7974
    [SIMP-7975]: https://simp-project.atlassian.net/browse/SIMP-7975

github:
  pr_user: op-ct
  approval_message: ':+1: :ghost:'
