---
jira:
  parent_issue: SIMP-7035
  projecte: SIMP
  jira_site: https://simp-project.atlassian.net
  subtask_title: 'Update .travis.yml pipeline in %COMPONENT%'
  subtask_story_points: 1
  subtask_description: 'Push the new (static) Travis CI pipelines to %COMPONENT%'
  assignee: '%SELF%'


github:
  user: op-ct

git:
  commit_msg: |
    (SIMP-7035) Update to new Travis CI pipeline

    This patch updates the Travis Pipeline to a static, standardized format
    that uses project variables for secrets. It includes an optional
    diagnostic mode to test the project's variables against their respective
    deployment APIs (GitHub and Puppet Forge).

    SIMP-7035 #comment Add new pipeline to %COMPONENT%
    %JIRA_SUBTASK% #close
