---

puppetsync:
  #puppet_role: 'role::pupmod'
  permitted_project_types:
    - pupmod_skeleton
    - pupmod
  plans:
    sync:
      #clone_git_repos: false
      stages:
        # - install_gems
        - checkout_git_feature_branch_in_each_repo
        - ensure_jira_subtask
        - apply_puppet_role
        - modernize_gitlab_files
        - lint_gitlab_ci
        - git_commit_changes
        - ensure_github_fork
        - ensure_git_remote
        - git_push_to_remote
          #- ensure_gitlab_remote
          #- git_push_to_gitlab
          #- ensure_github_pr


    approve_github_pr:
      clone_git_repos: false
      stages:
        - approve_github_pr_for_each_repo

    merge_github_pr:
      clone_git_repos: false
      stages:
        - merge_github_pr_for_each_repo


jira:
  parent_issue: SIMP-7977
  project: SIMP
  jira_site: https://simp-project.atlassian.net
  subtask_title: 'Update standardized assets in %COMPONENT%'
  # optional:
  # subtask_story_points: 1
  subtask_description: 'Update the %COMPONENT% repo to use the latest standardized assets'
  subtask_assignee: true

git:
  # 0---------1---------2---------3---------4---------5---------6---------7-|
  # (SIMP-XXXX) 123456789
  commit_message: |
    (%JIRA_PARENT_ISSUE%) Update standardized assets

    %JIRA_SUBTASK% #close
    [%JIRA_PARENT_ISSUE%] #comment Update %COMPONENT%

github:
  pr_user: op-ct
  approval_message: ':+1: :ghost:'
